const STRAVA_AUTH = 'https://www.strava.com/oauth/authorize'
const STRAVA_TOKEN = 'https://www.strava.com/oauth/token'
const STRAVA_API = 'https://www.strava.com/api/v3'

export default { async fetch(request, env) {
  const url = new URL(request.url), origin = request.headers.get('Origin')
  if (request.method === 'OPTIONS') return cors(new Response(null, { status: 204 }), origin, env)
  try {
    if (url.pathname === '/api/strava/callback') return callback(url, env)
    if (!url.pathname.startsWith('/api/strava/')) return json({ error: 'Not found' }, 404, origin, env)
    const user = await authenticate(request, env), path = url.pathname.replace('/api/strava/', '')
    if (path === 'connect' && request.method === 'POST') return cors(await connect(user, env), origin, env)
    if (path === 'status' && request.method === 'GET') return cors(await status(user, env), origin, env)
    if (path === 'activities' && request.method === 'GET') return cors(await activities(user, url, env), origin, env)
    if (path === 'disconnect' && request.method === 'POST') return cors(await disconnect(user, env), origin, env)
    return json({ error: 'Not found' }, 404, origin, env)
  } catch (error) { return json({ error: error.status === 500 ? 'Strava service failed.' : error.message }, error.status || 500, origin, env) }
} }
async function authenticate(request, env) { const header = request.headers.get('Authorization') || ''; if (!header.startsWith('Bearer ')) throw httpError(401, 'Sign in required.'); const response = await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${env.FIREBASE_API_KEY}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ idToken: header.slice(7) }) }); if (!response.ok) throw httpError(401, 'Your session has expired.'); const data = await response.json(); if (!data.users?.[0]?.localId) throw httpError(401, 'Invalid user.'); return { uid: data.users[0].localId } }
async function connect(user, env) { const state = crypto.randomUUID(); await env.STRAVA_TOKENS.put(`state:${state}`, JSON.stringify({ uid: user.uid }), { expirationTtl: 600 }); const url = new URL(STRAVA_AUTH); url.search = new URLSearchParams({ client_id: env.STRAVA_CLIENT_ID, redirect_uri: env.STRAVA_REDIRECT_URI, response_type: 'code', approval_prompt: 'auto', scope: 'activity:read_all', state }); return json({ url: url.toString() }) }
async function callback(url, env) { const state = url.searchParams.get('state'), code = url.searchParams.get('code'), error = url.searchParams.get('error'); const saved = state && await env.STRAVA_TOKENS.get(`state:${state}`, 'json'); if (state) await env.STRAVA_TOKENS.delete(`state:${state}`); if (!saved?.uid) return redirect(env, 'strava_error=invalid_state'); if (error || !code) return redirect(env, `strava_error=${encodeURIComponent(error || 'missing_code')}`); const response = await fetch(STRAVA_TOKEN, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ client_id: env.STRAVA_CLIENT_ID, client_secret: env.STRAVA_CLIENT_SECRET, code, grant_type: 'authorization_code' }) }); if (!response.ok) return redirect(env, 'strava_error=token_exchange'); const token = await response.json(); await env.STRAVA_TOKENS.put(`token:${saved.uid}`, JSON.stringify({ access_token: token.access_token, refresh_token: token.refresh_token, expires_at: token.expires_at, athlete: token.athlete, scope: url.searchParams.get('scope') || '' })); return redirect(env, 'strava=connected') }
async function status(user, env) { const token = await env.STRAVA_TOKENS.get(`token:${user.uid}`, 'json'); return json({ connected: Boolean(token), athlete: token?.athlete ? { id: token.athlete.id, firstname: token.athlete.firstname, lastname: token.athlete.lastname, profile_medium: token.athlete.profile_medium } : null, scope: token?.scope || null }) }
async function activities(user, url, env) { const token = await validToken(user.uid, env); if (!token) throw httpError(409, 'Connect Strava first.'); const page = clamp(url.searchParams.get('page'), 1, 1000, 1), perPage = clamp(url.searchParams.get('per_page'), 1, 100, 30), endpoint = new URL(`${STRAVA_API}/athlete/activities`); endpoint.search = new URLSearchParams({ page: String(page), per_page: String(perPage) }); const response = await fetch(endpoint, { headers: { Authorization: `Bearer ${token.access_token}` } }); if (!response.ok) throw httpError(response.status === 429 ? 429 : 502, response.status === 429 ? 'Strava rate limit reached. Try again later.' : 'Could not load Strava activities.'); const data = await response.json(); return json({ page, perPage, hasMore: data.length === perPage, activities: data.map(normalizeActivity), syncedAt: new Date().toISOString() }) }
async function validToken(uid, env) { let token = await env.STRAVA_TOKENS.get(`token:${uid}`, 'json'); if (!token) return null; if (Number(token.expires_at) > Math.floor(Date.now() / 1000) + 300) return token; const response = await fetch(STRAVA_TOKEN, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ client_id: env.STRAVA_CLIENT_ID, client_secret: env.STRAVA_CLIENT_SECRET, grant_type: 'refresh_token', refresh_token: token.refresh_token }) }); if (!response.ok) { await env.STRAVA_TOKENS.delete(`token:${uid}`); throw httpError(401, 'Reconnect Strava to continue.') } token = { ...token, ...await response.json() }; await env.STRAVA_TOKENS.put(`token:${uid}`, JSON.stringify(token)); return token }
async function disconnect(user, env) { const token = await validToken(user.uid, env); if (token) { const basic = btoa(`${env.STRAVA_CLIENT_ID}:${env.STRAVA_CLIENT_SECRET}`); await fetch('https://www.strava.com/oauth/revoke', { method: 'POST', headers: { Authorization: `Basic ${basic}`, 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ token: token.refresh_token, token_type_hint: 'refresh_token' }) }) } await env.STRAVA_TOKENS.delete(`token:${user.uid}`); return json({ connected: false }) }
function normalizeActivity(item) { return { id: String(item.id), name: item.name, type: item.sport_type || item.type, date: item.start_date_local, distanceKm: Number((item.distance / 1000).toFixed(2)), durationSeconds: item.moving_time, elapsedSeconds: item.elapsed_time, elevationGainM: item.total_elevation_gain, averageHeartRate: item.average_heartrate, maxHeartRate: item.max_heartrate, averagePowerWatts: item.average_watts, trainer: Boolean(item.trainer), commute: Boolean(item.commute) } }
function redirect(env, query) { return Response.redirect(`${env.APP_URL}/?${query}`, 302) }
function clamp(value, min, max, fallback) { const number = Number(value); return Number.isFinite(number) ? Math.min(max, Math.max(min, Math.round(number))) : fallback }
function httpError(status, message) { return Object.assign(new Error(message), { status }) }
function json(data, status = 200, origin, env) { return cors(new Response(JSON.stringify(data), { status, headers: { 'Content-Type': 'application/json' } }), origin, env) }
function cors(response, origin, env) { if (!env) return response; const allowed = (env.ALLOWED_ORIGINS || env.APP_URL).split(',').map(value => value.trim()); if (origin && allowed.includes(origin)) { response.headers.set('Access-Control-Allow-Origin', origin); response.headers.set('Vary', 'Origin'); response.headers.set('Access-Control-Allow-Headers', 'Authorization, Content-Type'); response.headers.set('Access-Control-Allow-Methods', 'GET, POST, OPTIONS') } return response }